name: Rust CI

on: ["push", "pull_request"]

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy (Linter)
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --verbose
